// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the Game Data Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System;
using System.Collections.Generic;

using GameDataEditor;

namespace GameDataEditor
{
    public class GDEBuff_DemoData : IGDEData
    {
        static string hp_deltaKey = "hp_delta";
		int _hp_delta;
        public int hp_delta
        {
            get { return _hp_delta; }
        }

        static string mana_deltaKey = "mana_delta";
		int _mana_delta;
        public int mana_delta
        {
            get { return _mana_delta; }
        }

        static string damage_deltaKey = "damage_delta";
		int _damage_delta;
        public int damage_delta
        {
            get { return _damage_delta; }
        }

        static string nameKey = "name";
		string _name;
        public string name
        {
            get { return _name; }
        }

        public GDEBuff_DemoData(string key) : base(key) {}

        public override void LoadFromDict(string dataKey, Dictionary<string, object> dict)
        {
            _key = dataKey;

			if (dict == null)
				return;
			else
			{
                dict.TryGetInt(hp_deltaKey, out _hp_delta);
                dict.TryGetInt(mana_deltaKey, out _mana_delta);
                dict.TryGetInt(damage_deltaKey, out _damage_delta);
                dict.TryGetString(nameKey, out _name);
            }
		}

    }
}
