// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the Game Data Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System;
using System.Collections.Generic;

using GameDataEditor;

namespace GameDataEditor
{
    public class GDECharacter_DemoData : IGDEData
    {
        static string hpKey = "hp";
		int _hp;
        public int hp
        {
            get { return _hp; }
        }

        static string manaKey = "mana";
		int _mana;
        public int mana
        {
            get { return _mana; }
        }

        static string damageKey = "damage";
		int _damage;
        public int damage
        {
            get { return _damage; }
        }

        static string nameKey = "name";
		string _name;
        public string name
        {
            get { return _name; }
        }

        static string buffsKey = "buffs";
		public List<GDEBuff_DemoData>      buffs;

        public GDECharacter_DemoData(string key) : base(key) {}

        public override void LoadFromDict(string dataKey, Dictionary<string, object> dict)
        {
            _key = dataKey;

			if (dict == null)
				return;
			else
			{
                dict.TryGetInt(hpKey, out _hp);
                dict.TryGetInt(manaKey, out _mana);
                dict.TryGetInt(damageKey, out _damage);
                dict.TryGetString(nameKey, out _name);

                dict.TryGetCustomList(buffsKey, out buffs);
            }
		}

    }
}
