// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the Game Data Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System;

namespace GameDataEditor
{
    public class GDEDemoItemKeys
    {
        public static string Character_Demo_warrior = "warrior";
        public static string Buff_Demo_life_surge_1 = "life_surge_1";
        public static string Buff_Demo_dmg_surge_1 = "dmg_surge_1";
        public static string Buff_Demo_warrior_aura_1 = "warrior_aura_1";
    }
}
